sudo: required

language: java

services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
    - DOCKER_COMPOSE_VERSION=1.6.0

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install docker-engine=${DOCKER_VERSION}
  - sudo gpasswd -a $USER docker
  - export USER_ID=`id -u $USER`
  - docker -v

  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v

  - ./rename.py travis

install:
  - docker-compose -f docker-compose.yml -f docker-compose.unix.yml build

script:
  - docker-compose -f docker-compose.yml -f docker-compose.unix.yml up -d

  - docker inspect -f {{.State.Running}} devspace_jenkins_1
  - d=10; while ! docker logs devspace_jenkins_1 2>&1 | grep "Jenkins is fully up and running" ; do sleep 10; d=$[$d -1]; if [ $d -lt 0 ]; then exit 1; fi; done
  - docker inspect -f {{.State.Running}} devspace_pg_1
  - docker inspect -f {{.State.Running}} devspace_redis_1
  - docker inspect -f {{.State.Running}} devspace_slave_1
  - docker inspect -f {{.State.Running}} devspace_omero_1
  - docker inspect -f {{.State.Running}} devspace_web_1
  - docker inspect -f {{.State.Running}} devspace_nginx_1
  - docker inspect -f {{.State.Running}} devspace_robot_1

  - docker inspect -f {{.State.Running}} devspace_seleniumhub_1
  - docker inspect -f {{.State.Running}} devspace_seleniumfirefox_1
  - docker inspect -f {{.State.Running}} devspace_seleniumchrome_1

  - SLAVE_ADDR=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' devspace_slave_1`
  - d=10; while ! docker logs devspace_jenkins_1 2>&1 | grep "from /${SLAVE_ADDR}" ; do sleep 10; d=$[$d -1]; if [ $d -lt 0 ]; then echo "Didn't connect?"; exit 1; fi; done

  - SLAVE_ADDR=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' devspace_omero_1`
  - d=10; while ! docker logs devspace_jenkins_1 2>&1 | grep "from /${SLAVE_ADDR}" ; do sleep 10; d=$[$d -1]; if [ $d -lt 0 ]; then echo "Didn't connect?"; exit 1; fi; done
  - docker exec -it devspace_omero_1 /bin/bash -c "service jenkins status -l"

  - SLAVE_ADDR=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' devspace_web_1`
  - d=10; while ! docker logs devspace_jenkins_1 2>&1 | grep "from /${SLAVE_ADDR}" ; do sleep 10; d=$[$d -1]; if [ $d -lt 0 ]; then echo "Didn't connect?"; exit 1; fi; done
  - docker exec -it devspace_web_1 /bin/bash -c "service jenkins status -l"

  - SLAVE_ADDR=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' devspace_nginx_1`
  - d=10; while ! docker logs devspace_jenkins_1 2>&1 | grep "from /${SLAVE_ADDR}" ; do sleep 10; d=$[$d -1]; if [ $d -lt 0 ]; then echo "Didn't connect?"; exit 1; fi; done
  - docker exec -it devspace_nginx_1 /bin/bash -c "service jenkins status -l"

  - SLAVE_ADDR=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' devspace_robot_1`
  - d=10; while ! docker logs devspace_jenkins_1 2>&1 | grep "from /${SLAVE_ADDR}" ; do sleep 10; d=$[$d -1]; if [ $d -lt 0 ]; then echo "Didn't connect?"; exit 1; fi; done
  - docker exec -it devspace_robot_1 /bin/bash -c "service jenkins status -l"

  - docker-compose -f docker-compose.yml -f docker-compose.unix.yml stop
