storage:
  image: redis
  volumes:
        - /var/lib/docker/registry
  command: true

jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home
    environment:
        SERVICE_NAME

git:
    image: openmicroscopy/tags:5.1.1
    volumes:
        - /src
    command: true

pg:
    image: postgres

nginx:
    image: nginx

slave:
    build: slave
    links:
        - jenkins
        - nginx
        - pg
    volumes_from:
        - git
