jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home
    environment:
        - SERVICE_NAME=SPACENAME-ci

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres
    volumes:
        - ./pgdata:/var/lib/postgresql/data

testice35:
    build: slave
    links:
        - pg
        - jenkins
    volumes:
        - ./slave:/home/omero
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels ice35 -name testice35 -disableClientsUniqueId -executors 4"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-testice35

testice36:
    build: slave2
    links:
        - pg
        - jenkins
    volumes:
        - ./slave2:/home/omero
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels ice36 -name testice36 -disableClientsUniqueId -executors 4"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-testice36

omero:
    build: server
    links:
        - jenkins
        - pg
    volumes:
        - ./server:/home/omero
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels ice35 -name omero -disableClientsUniqueId -executors 4"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-omero

webice35:
    build: web
    links:
        - jenkins
        - redis
        - omero
        - testice35
        - testice36
    volumes:
        - ./web:/home/omero
        - ./nginx/conf.d:/home/omero/nginx
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels ice35 -name webice35 -disableClientsUniqueId -executors 4"
        - JENKINS_MODE=exclusive

nginx:
    build: nginx
    links:
        - jenkins
        - webice35
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./web/static/web:/home/omero/static/web
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels nginx -name nginx -disableClientsUniqueId -executors 1"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-nginx

redis:
    image: redis
    environment:
        - SERVICE_NAME=SPACENAME-redis

seleniumhub:
    image: selenium/hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
        - SERVICE_NAME=SPACENAME-seleniumhub
        - GRID_BROWSER_TIMEOUT=5000
        - GRID_TIMEOUT=5000
seleniumfirefox:
    image: selenium/node-firefox
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
seleniumchrome:
    image: selenium/node-chrome
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"

robot:
    build: robot
    links:
        - jenkins
        - nginx
        - seleniumhub
        - omero
        - testice35
        - testice36
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels ice35 -name robot -disableClientsUniqueId -executors 4"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-robot
