jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home
    environment:
        - SERVICE_NAME=SPACENAME-ci

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres

slave:
    build: slave
    links:
        - pg
        - jenkins
    volumes:
        - ./slave:/home/slave
    environment:
        - JAVA_HOME=/etc/alternatives/java_sdk
        - DOCKER_FIX='   '
    command: -labels centos6 -labels slave -executors 4

omero:
    build: server
    links:
        - jenkins
        - pg
    volumes:
        - ./server:/home/omero
    environment:
        - JENKINS_LABEL=/etc/alternatives/java_sdk
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-omero

web:
    build: web
    links:
        - jenkins
        - redis
        - slave
        - omero
    volumes:
        - ./web:/home/omero
        - ./nginx/conf.d:/home/omero/nginx
    environment:
        - JENKINS_LABEL=/etc/alternatives/java_sdk
        - JENKINS_MODE=exclusive

nginx:
    build: nginx
    links:
        - jenkins
        - web
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./web/static/web:/home/omero/static/web
    environment:
        - JENKINS_LABEL=/etc/alternatives/java_sdk
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-nginx

redis:
    image: redis
    environment:
        - SERVICE_NAME=SPACENAME-redis

seleniumhub:
    image: selenium/hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
        - SERVICE_NAME=SPACENAME-seleniumhub
        - GRID_BROWSER_TIMEOUT=5000
        - GRID_TIMEOUT=5000
seleniumfirefox:
    image: selenium/node-firefox
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
seleniumchrome:
    image: selenium/node-chrome
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"

robot:
    build: robot
    links:
        - jenkins
        - slave
        - omero
        - nginx
        - seleniumhub
    environment:
        - JENKINS_LABEL=/etc/alternatives/java_sdk
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-robot
