home:
    build: home
    volumes:
        - /var/jenkins_home
    command: true

storage:
  image: redis
  volumes:
        - /var/lib/docker/registry
  command: true

cache:
    image: redis

backend:
  image: registry
  ports:
        - 127.0.0.1:5000:5000
  links:
        - cache
  volumes_from:
        - storage
  environment:
    SETTINGS_FLAVOR: local
    STORAGE_PATH: /var/lib/docker/registry
    SEARCH_BACKEND: sqlalchemy
    CACHE_REDIS_HOST: cache
    CACHE_REDIS_PORT: 6379
    CACHE_LRU_REDIS_HOST: cache
    CACHE_LRU_REDIS_PORT: 6379

frontend:
  image: konradkleine/docker-registry-frontend
  ports:
        - 127.0.0.1:8081:80
  environment:
    ENV_DOCKER_REGISTRY_HOST: backend
    ENV_DOCKER_REGISTRY_PORT: 5000

jenkins:
    build: jenkins
    volumes_from:
        - home

git:
    image: openmicroscopy/tags:5.1.1
    volumes:
        - /src
    command: true

slave:
    build: slave
    links:
        - jenkins
    volumes_from:
        - git
