jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home
    environment:
        - SERVICE_NAME=SPACENAME-ci

git:
    image: openmicroscopy/tags:5.1.1
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres

slave:
    build: slave
    links:
        - pg
        - jenkins
    volumes:
        - ./slave:home/jenkins-slave
    volumes_from:
        - git
    environment:
        - JAVA_HOME=/etc/alternatives/java_sdk

nginx:
    image: nginx
    links:
        - slave
    volumes:
        - ./slave:home/jenkins-slave
    environment:
        - SERVICE_NAME=SPACENAME-web
