jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home
    environment:
        - SERVICE_NAME=SPACENAME-ci

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres
    volumes:
        - ./pgdata:/var/lib/postgresql/data

test:
    build: slave
    links:
        - pg
        - jenkins
    volumes:
        - ./slave:/home/omero
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels test -executors 4"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-test

testice:
    build: slave2
    links:
        - pg
        - jenkins
    volumes:
        - ./slave2:/home/omero
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels testice -executors 4"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-testice

omero:
    build: server
    links:
        - jenkins
        - pg
    volumes:
        - ./server:/home/omero
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels omero -executors 4"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-omero

web:
    build: web
    links:
        - jenkins
        - redis
        - omero
        - test
        - testice
    volumes:
        - ./web:/home/omero
        - ./nginx/conf.d:/home/omero/nginx
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels web -executors 4"
        - JENKINS_MODE=exclusive

nginx:
    build: nginx
    links:
        - jenkins
        - web
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./web/static/web:/home/omero/static/web
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels nginx  -executors 1"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-nginx

redis:
    image: redis
    environment:
        - SERVICE_NAME=SPACENAME-redis

seleniumhub:
    image: selenium/hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
        - SERVICE_NAME=SPACENAME-seleniumhub
        - GRID_BROWSER_TIMEOUT=5000
        - GRID_TIMEOUT=5000
seleniumfirefox:
    image: selenium/node-firefox
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"
seleniumchrome:
    image: selenium/node-chrome
    links:
        - seleniumhub:hub
    environment:
        - "JAVA_OPTS: -d64 -Xmx512m -Djava.security.egd=file:/dev/./urandom"

robot:
    build: robot
    links:
        - jenkins
        - nginx
        - seleniumhub
        - omero
        - test
        - testice
    environment:
        - SWARM_PARAMS=" -labels centos7 -labels robot -executors 4"
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-robot
