jenkins:
    build: jenkins
    volumes:
        - ./home:/var/jenkins_home
    environment:
        - SERVICE_NAME=SPACENAME-ci

git:
    build: git
    volumes:
        - /src
    command: 'true'

pg:
    image: postgres

slave:
    build: slave
    links:
        - pg
        - jenkins
    volumes:
        - ./slave:/home/slave
    volumes_from:
        - git
    environment:
        - JAVA_HOME=/etc/alternatives/java_sdk
        - SERVICE_NAME=SPACENAME-omero
        - DOCKER_FIX='   '
    command: -labels java -labels slave -name slave -disableClientsUniqueId -executors 4

web:
    build: web
    links:
        - jenkins
    environment:
        - JENKINS_LABEL=/etc/alternatives/java_sdk
        - JENKINS_MODE=exclusive
        - SERVICE_NAME=SPACENAME-omero
    volumes:
        - ./web:/home/omero
    command: -labels centos7 -labels java -name web -disableClientsUniqueId -executors 4
    

nginx:
    image: nginx
    links:
        - slave
        - web
    volumes:
        - ./slave:/home/jenkins-slave
    environment:
        - SERVICE_NAME=SPACENAME-web
